package constants

const (
	EVENT_NAME_SAGASTARTEDEVENT = "SagaStartedEvent"
	EVENT_NAME_TXSTARTEDEVENT = "TxStartedEvent"
	EVENT_NAME_TXENDEDEVENT = "TxEndedEvent"
	EVENT_NAME_TXABORTEDEVENT = "TxAbortedEvent"
	EVENT_NAME_TXCOMPENSATEDEVENT = "TxCompensatedEvent"
	EVENT_NAME_SAGAENDEDEVENT = "SagaEndedEvent"
)
