package constants

const (
	KEY_FUNCTION_CALL_ARGS = "KEY_FUNCTION_CALL_ARGS"
	KEY_FUNCTION_CALL_ERROR = "KEY_FUNCTION_CALL_ERROR"
	KEY_PARENT_LOCAL_TX_ID = "KEY_PARENT_LOCAL_TX_ID"
	KEY_SAGA_AGENT_CONTEXT = "KEY_SAGA_AGENT_CONTEXT"

	KEY_GLOBAL_TX_ID_KEY = "X-Pack-Global-Transaction-Id"
	KEY_LOCAL_TX_ID_KEY = "X-Pack-Local-Transaction-Id"
)
